defaults:
  - _self_
  - launcher: local   #what does this local mean?
  - data: pusht     
  - model: lewm   #model: le world model

output_model_name: lewm
subdir: ${hydra:job.id}  #subdir: hydra:job.id

num_workers: 6  #num of workers used for what reasons?
train_split: 0.9 #90%
seed: 3072 #3072 
img_size: 224 #224x224
embed_dim: 192 #Z(dim) : 192
history_size: 3 #what does history size 3 mean

trainer:
  max_epochs: 100  #max epochs 100
  devices: auto #what does assigning device value to auto means?
  accelerator: gpu 
  precision: bf16 #batch frame 16 what are the other values and whats the use of this ?
  gradient_clip_val: 1.0 

loader:
  batch_size: 128  #batch size is 128
  num_workers: ${num_workers} #number of workers why are they used
  persistent_workers: True
  prefetch_factor: 3
  pin_memory: True

optimizer:
  type: AdamW
  lr: 5e-5
  weight_decay: 1e-3

num_preds: 1

loss:
  sigreg:
    weight: 0.09
    kwargs:
      knots: 17
      num_proj: 1024
  aux_ee:
    weight_trans: 0.1
    weight_rot: 0.5  #weighted higher isince this is the failure mode we are targeting 
    weight_grip: 0.1
